services:
  ray-head:
    build: .
    container_name: ray-head
    shm_size: '2gb'
    ports:
      - "8000:8000"
      - "8265:8265"
      - "8080:8080"
    environment:
      - RAY_PROMETHEUS_HOST=http://prometheus:9090
      - RAY_PROMETHEUS_NAME=Prometheus
      - RAY_GRAFANA_HOST=http://grafana:3000
      - RAY_GRAFANA_IFRAME_HOST=http://localhost:3000
    command: bash start_node.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/-/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus-docker.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/provisioning/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
    depends_on:
      - prometheus
