[project]
name = "rayserve-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.4.1",
    "ray[serve]>=2.53.0",
    "requests>=2.32.5",
    "scikit-learn>=1.8.0",
    "starlette>=0.50.0",
]
