apiVersion: v1
kind: Service
metadata:
  name: rayserve-demo-expose
spec:
  type: NodePort
  selector:
    app: rayserve-demo-head
  ports:
  - name: serve
    port: 8000
    targetPort: 8000
    nodePort: 30000
  - name: dashboard
    port: 8265
    targetPort: 8265
    nodePort: 30265
  - name: metrics
    port: 8080
    targetPort: 8080
